### ISSUE TITLE
[To do] web/voting       mongodb schema 구성

### ISSUE THREAD

**Issue by omago123** [DaeguDev/MeowRun#122]
## 설명
튜토리얼 진행을 통하여 schema 구성을 어떻게 하는지 익힌뒤에 voting schema 구성을 완료할 예정

## To do
- [ ] mongodb schema tutorial 진행
- [ ] voting schema 작성

**Comment by developerasun** [comment]
## 변경 내용 
@omago123 프로젝트 중단, 이슈 클로징
