### ISSUE TITLE
[BUG] Unity/Player : 점프 로직

### ISSUE THREAD

**Issue by developerasun** [DaeguDev/MeowRun#126]
**해당 버그를 설명해주세요**
플레이어 3D 지형 점프 버그 (아래 영상은 점프 키 없이 방향키로만 움직인 영상입니다)

**버그 확인**
다른 팀원들이 해당 버그를 확인하기 위해 스크린샷 또는 동영상을 첨부해주세요. 가능하다면, 어떻게 해서 버그를 생성할 수 있는지 스텝별로 설명해주세요. 

https://user-images.githubusercontent.com/83855174/163103472-702baa0d-4635-40d6-82a6-d2e1225d86fe.mp4

예시 : Steps to reproduce the behavior:
1. Go to Scenes/Playground.scene
2. Move characters towards cliffs
3. See error

**버그 해결 과정**
- 어떤 식으로 버그를 해결했나요? : 
- 버그 해결 이후 어떻게 동작하나요? 

**추가 정보(선택) **
- 메모 또는 예기치 못했던 점들을 서술해주세요 : 

**라벨 지정** 
- 적절한 라벨을 지정해주세요: e.g bug, unity/c#

**Comment by jshhhhh** [comment]
ㅋㅋㅋㅋ이 문제 인지는 하고 있는데.. 나중에 로직 수정하든지 대대적으로 손 좀 봐야 할 듯
