### ISSUE TITLE
[BUG] clone 후 프리펩이 제대로 표시되지 않는 문제

### ISSUE THREAD

**Issue by jshhhhh** [DaeguDev/MeowRun#164]
**해당 버그를 설명해주세요**
#158 merge 후 테스트 목적으로 빈 폴더에 git clone했음
프리펩 오류 및 씬에 나타나지 않는 문제 발생

**버그 확인**

* 씬에서 Player, 아이템(can, skull 등) 프리펩이 보이지 않음

![프리펩 실종](https://user-images.githubusercontent.com/86046319/169517814-a26e5d91-f79d-4ba0-a80c-0b34709b8aaf.png)

* 오류 로그

![missing prefab 1](https://user-images.githubusercontent.com/86046319/169517966-bc7badf2-0253-4a34-b6b3-0c023d571e31.png)

* 하이어라키에서 Missing Prefab with guide

![하이어라키](https://user-images.githubusercontent.com/86046319/169518273-deb9ecdf-6fe5-42c9-b6c6-fb2fc20f5e4b.png)

* 프리펩 편집 페이지

![missing prefab 2](https://user-images.githubusercontent.com/86046319/169518572-a5e9105c-5092-4bc8-a24d-70ecb2ccfffb.png)

예시 : Steps to reproduce the behavior:
1. [MeowRun](https://github.com/DaeguDev/MeowRun.git) git clone하기
2. 프로젝트 열기
3. See error

**버그 해결 과정**
- 어떤 식으로 버그를 해결했나요? : 해결 중
- 버그 해결 이후 어떻게 동작하나요? 

**추가 정보(선택) **
- 메모 또는 예기치 못했던 점들을 서술해주세요 : 

**라벨 지정** 
- bug, unity/c#, help, working-on

**Comment by developerasun** [comment]
Playground씬에서 계속 작업한 거 완성되면 dev씬으로 옮겨보세요 

https://github.com/DaeguDev/MeowRun/discussions/146

**Comment by jshhhhh** [comment]
> ## 해결 시도
* #158 merge 후 문제가 발생했나 싶어 mege 전 생성해놓은 [MeowRun Test Release v0.4](https://github.com/DaeguDev/MeowRun/releases/tag/pre-release-v0.4) 확인

![릴리즈](https://user-images.githubusercontent.com/86046319/169522120-c4bb3259-1a71-4773-b121-04a6c821d863.png)

* [MeowRun Test Release v0.4](https://github.com/DaeguDev/MeowRun/releases/tag/pre-release-v0.4)에서 오류 로그는 없었지만 프리펩 미표시 및 Missing Prefab with guide 확인

![릴리즈 씬](https://user-images.githubusercontent.com/86046319/169522140-7f201855-0927-4f94-9bc9-c4838f610ab7.png)

**Comment by jshhhhh** [comment]
> ## 해결 시도

* 테스트 폴더에서 log 확인 후 merge 전 커밋으로 reset 시도

![커밋](https://user-images.githubusercontent.com/86046319/169522640-f5f7b1a4-0495-4171-a1b7-4fd4129f51f4.png)
도

* lfs 이슈로 reset이 막힘

![용량 문제](https://user-images.githubusercontent.com/86046319/169522657-243104dd-66f3-46ce-9f6b-e0c3538ca378.png)

**Comment by developerasun** [comment]
Enmey 프리팹들 완성본들은 dev 씬에 있음 - #146 에서 언급했듯에 playground 작업물들 완성되면 dev로 옮겨놔서 기존 playground에 배치해놨던 enemy들은 삭제해둠. 

필요하면 dev씬 계층 창에서 enemy/potion 객체 통째로 복사해오면 될 듯

**Comment by jshhhhh** [comment]
> Enmey 프리팹들 완성본들은 dev 씬에 있음 - #146 에서 언급했듯에 playground 작업물들 완성되면 dev로 옮겨놔서 기존 playground에 배치해놨던 enemy들은 삭제해둠.
> 
> 필요하면 dev씬 계층 창에서 enemy/potion 객체 통째로 복사해오면 될 듯
> 
> LFS이슈 같은 경우는 전에도 말씀드렸지만 일단 문제되는 .png 텍스처 삭제 - 커밋 - 하고 알파값 배경으로 선 진행하고 기능 마무리 이후에 terrain 질감 표현만 마무리 하자고 논의된 거니까

playground 씬뿐만 아니라 dev 씬도 오브젝트 전부가 나타나지 않음
- 초록색 박스로 콜라이더만 표시됨

![날라감 1](https://user-images.githubusercontent.com/86046319/169641499-7240a663-cc11-4cd3-aa04-f92e68028cc3.png)

dev 씬에서의 enemy 상태

![날라감 2](https://user-images.githubusercontent.com/86046319/169641513-ac98b9ba-d8ec-4f95-b87b-4d8c405eab9f.png)

beeSting Variant 프리펩 편집 창 (Missing Prefab with guide 이슈)
* 다른 모든 enemy 프리펩, item 프리펩도 다 이런 상태임

![날라감 3](https://user-images.githubusercontent.com/86046319/169641608-519af1ad-5ab7-46e8-bdb1-6d882b32b99c.png)

로컬에 작업하던 저장소가 남아 있어서 이걸 어떻게든 업로드하면 해결될 거 같긴 한데..
PR merge 전부터 이미 이런 상태였던 것으로 추측됨
Missing Prefab with guide 이슈 관련해서 [이 글](https://forum.unity.com/threads/missing-prefabs-and-components-after-cloning-fresh-from-gitlab.1215912/)이 좀 도움될 거 같아서 가져와 봤는데, 영문 페이지라 혹시 보고 좋은 내용 있으면 알려주셈

**Comment by jshhhhh** [comment]
오히려 [포크 레포](https://github.com/jshhhhh/MeowRun) clone했는데 왜 멀쩡하지?
이거 때문에 진행도 못 하고 머리 아프네..

![1](https://user-images.githubusercontent.com/86046319/169647565-601f9fa6-891e-4690-bcdd-060c382afc9c.png)

![2](https://user-images.githubusercontent.com/86046319/169647566-d3813cec-f7f8-4f52-81f5-a547f0351bdf.png)

**Comment by developerasun** [comment]
> 오히려 [포크 레포](https://github.com/jshhhhh/MeowRun) clone했는데 왜 멀쩡하지?
> 이거 때문에 진행도 못 하고 머리 아프네..
> 

보니까 현재 main 브랜치에는 Resources 디렉토리 없고 포킹 레포에는 Resources 있는 거보니까 그거 때문인가 싶기도 하네요 니잔에 Resources 날리고 작업한 PR에서 문제된건가

**Comment by developerasun** [comment]
포킹된 레포에서 주요 기능 체크해보고 문제없으면 메인에 브랜치에 덮어쓰는 건 어떤가유

**Comment by developerasun** [comment]
1. 깃허브 원격 저장소 유니티 프로젝트 삭제
2. 로컬 브랜치 작업물 업로드 및 롤백 포인트로 지정 
3. #168 에서 추후 브랜치 전략 등 논의
