### ISSUE TITLE
[BUG] BoxCast가 경사진 지형을 인식 못 함

### ISSUE THREAD

**Issue by jshhhhh** [DaeguDev/MeowRun#28]
# issue : BoxCast가 경사진 지형을 인식 못 함
## screenshot : attach a screenshot showing the bug
* 평지에서의 체크(파란색 Box가 평지를 인식함)

![image](https://user-images.githubusercontent.com/86046319/159125610-3517f4b1-378b-4dbe-b09d-182ee8af5beb.png)

* 경사진 곳에서의 체크(빨간색 Ray가 지형을 인식하지 못하고 통과함)

![image](https://user-images.githubusercontent.com/86046319/159125668-3209eed0-6cc7-46db-b47c-58f28933a374.png)

> ## 기울기에 따른 BaxCast 테스트
* 기울기가 없을 때만 바닥을 인식 - 기존의 RayCast 착지 인식 로직과 차이가 없음

https://user-images.githubusercontent.com/86046319/159289025-e5bee3a4-796b-40a0-afb2-ea5872191e41.mp4

## label : add propel lables for the bug

**Comment by developerasun** [comment]
ㅋㅋㅋ 점프 로직이 애를 썩이는 구나... 저는 중급 난이도 enemy 코루틴에 애를 먹고 있음

**Comment by developerasun** [comment]
좀 찾아보니까 raycast 여러 개를 여러 방향으로 쏘는 거랑  Vector 내/외적 써보라고 하네유. 검색 키워드는 unity ground check slope 

> If you know the normal vector of the surface you're standing on from a raycast, you can get the slope with:

```cs
float FindSurfaceSlope (Vector3 surfNormal) {

return Vector3.Angle (surfNormal, Vector3.up);

}
```

## 레퍼런스 
https://answers.unity.com/questions/1355054/how-to-know-the-slope-of-terrain-in-unity-when-i-p.html

**Comment by jshhhhh** [comment]
> 그럼 캐릭터를 딛고 있는 지형 각도에 맞춰서 로테이션 시키고 ray 쏴보면 어때요? 보니까 지금 지형만 기울여서 테스트 하는 거 같은데 기울어진 지형만큼 캐릭터도 기울일 수 있으면 이론 상 레이도 그만큼 기울여지지 않나

맵의 기울기에 따라서 물리법칙에 의해 기울기가 바뀌면 구현이 편할 텐데,

https://user-images.githubusercontent.com/86046319/159413852-b7f58be5-4ab0-4dc8-af6b-60314b730a94.mp4

Rigidbody의 Freeze Rotation을 풀었음에도 위 영상처럼 기울기가 변하지 않음
혹시 몰라서 Physics Material도 해제해봤는데 효과 없었음

https://user-images.githubusercontent.com/86046319/159413089-d48d35be-945f-45f0-9f17-5c205ea621d6.mp4

Collider도 종류별로 바꿔봤지만 역시나 기울어지지 않음

결국 Ray를 쓰든지, 플레이어의 발쪽에 자식 객체로 빈 오브젝트 생성하고 Collider 설정해서 충돌 체크하는 방법밖에 없을 듯

**Comment by developerasun** [comment]
개발이 어려운 게 겉으로 보기에는 간단해보이더라도 막상 열고 보면 복잡한 경우가 다반수라.. :) 이번에 토픽 하나 쭉 파보면서 많이 성장한 듯

**Comment by jshhhhh** [comment]
# test : 기울기에 따른 BaxCast 테스트
> ## 문제
* Rigidbody를 적용시켰음에도 플레이어 오브젝트가 기울어지지 않음

![image](https://user-images.githubusercontent.com/86046319/159746047-2a84eaa0-54ad-46eb-a331-3a5aa0d820c0.png)

> ## 해결
* playerDie 애니메이션에 적용된 Rotation 속성을 제거함으로써 해결
* 모종의 이유로 Rotation 속성이 오브젝트의 기울임을 방해한 것으로 추측

https://user-images.githubusercontent.com/86046319/159745625-43962fea-e89b-4526-aff3-777107ee01ae.mp4

> ## 테스트
* BoxCast가 함께 기울어지지는 않았지만, 경사진 지형을 정상적으로 인식하는 것을 확인

![image](https://user-images.githubusercontent.com/86046319/159747044-63eb42e7-5ded-492f-9380-da0d3e80bd85.png)
