### ISSUE TITLE
[BUG] ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by omago123** [DaeguDev/MeowRun#49]
# issue : server.js에서 해당 모듈을 찾지 못함
## screenshot : attach a screenshot showing the bug
![화면 캡처 2022-03-24 192846](https://user-images.githubusercontent.com/73014464/159897242-61d17e38-7614-4fb2-b394-31edc11e31d2.png)

**Comment by developerasun** [comment]
터미널 오류에서 제시한대로 .js 확장자 명 붙여보셨나용

**Comment by omago123** [comment]
.js 확장자 명을 붙이니 해결되었습니다.

#### before
![before](https://user-images.githubusercontent.com/73014464/159901094-b5c192f7-1945-480e-8246-57110d5fcf02.png)

#### after
![after](https://user-images.githubusercontent.com/73014464/159901413-91ba6fd9-c9e7-49d3-93c4-7de965f5111d.png)
