### ISSUE TITLE
[BUG] This branch has conflicts that must be resolved

### ISSUE THREAD

**Issue by jshhhhh** [DaeguDev/MeowRun#75]
# issue : 충돌로 인해 Pull request가 안 되는 문제 #65 
## screenshot : attach a screenshot showing the bug
> ## 발단
* "This branch has conflicts that must be resolved"라는 문구와 함께 Pull request가 안 됨

![image](https://user-images.githubusercontent.com/86046319/160271265-6c772534-a1fc-4f27-8ddd-dd88cf9117e3.png)

* 처음 아래의 해결 방법을 시도했지만 push 성공 완료만 뜨고 현상은 그대로였음

![image](https://user-images.githubusercontent.com/86046319/160271660-49b80a92-7141-4d46-8de9-4581981a48bb.png)

> ## 해결 과정

1. 오랫동안 본 레포에서 포크 레포로 pull을 진행하지 않아서 본 레포 : main → 포크 레포 : main Pull request 시도

![포크 레포에서 PR](https://user-images.githubusercontent.com/86046319/160271477-9f2951d1-ce1d-40a8-b3c5-e3468f310e5c.jpg)

2. 아래의 해결 방법 시도

![포크 레포에서 해결책](https://user-images.githubusercontent.com/86046319/160271781-30317dc2-5e76-4627-bde4-9e9eebba858b.jpg)

3. pr이라는 브렌치를 만들어 본 레포의 main 브렌치를 pull

![merge 요구](https://user-images.githubusercontent.com/86046319/160271827-4d4a4370-4406-4b17-a2f7-b061294859d0.jpg)

4. status에서 Unmerged 된 파일들 확인

![git status 확인](https://user-images.githubusercontent.com/86046319/160271881-9e6738ad-72e9-470f-b064-834105f2d0fe.jpg)
![git status 결과](https://user-images.githubusercontent.com/86046319/160271889-ed69c218-9111-4634-9e98-00da78d8be8e.jpg)

5. 마저 진행 후 포크 레포의 main에 Pull request 성공

![진행 1](https://user-images.githubusercontent.com/86046319/160271928-75a6c597-bd2d-4edc-9519-ee8539f0b1f4.jpg)
![merge](https://user-images.githubusercontent.com/86046319/160271932-437c68b5-1410-4aa5-a1b7-09aaacefa2ff.jpg)
![포크 레포에 pr 성공](https://user-images.githubusercontent.com/86046319/160271936-e4fadcd9-6fec-4f88-a037-f6bbd7a13b94.jpg)

6. 다시  포크 레포 : player → 본 레포 : main pull request 진행, push 성공했지만 충돌 해결 실패

![본 레포 해결책](https://user-images.githubusercontent.com/86046319/160272051-dc5dcfce-05e9-461b-bdd5-7d132dfdf4da.jpg)
![본 레포 pr 시도](https://user-images.githubusercontent.com/86046319/160272061-e4bd36ae-1685-421f-93f1-4aab7649c1b5.jpg)

7. 본 레포 : main → 포크 레포 : player Pull request 시도

![본 레포에서 포크 레포의 player 브랜치로 pr](https://user-images.githubusercontent.com/86046319/160272163-351817b2-a98f-4d4f-aac2-ea4229e7d772.jpg)
![player 브렌치 해결책](https://user-images.githubusercontent.com/86046319/160272166-4ef1fd97-3037-46f7-a64c-a2f2d76405ff.jpg)
![image](https://user-images.githubusercontent.com/86046319/160272182-56c085d6-2a19-487c-93be-b6f234161825.png)
![image](https://user-images.githubusercontent.com/86046319/160272327-40fe2188-e122-422d-834c-2cc2eea6460a.png)

8. 충돌 문구 사라진 것 확인

![image](https://user-images.githubusercontent.com/86046319/160272198-633c6590-e784-475b-bbfa-30cd7fea0db9.png)

## label : add propel lables for the bug

**Comment by developerasun** [comment]
와 생각보다 복잡한데??

**Comment by jshhhhh** [comment]
> 와 생각보다 복잡한데?? 해결할 수 있었던 중요 포인트가 뭐에요?

포크 레포의 main 최신화는 의미가 없었던 것 같고, 결국 pull request할 player 브렌치를 pull 땡겨서 본 레포의 main이랑 맞추는 게 중요했던 거 같음 ㅋㅋㅋ
