### ISSUE TITLE
[To do] 웹서버/몽고DB schema 설정

### ISSUE THREAD

**Issue by omago123** [DaeguDev/MeowRun#79]
## 설명
몽고DB schema 짜는 법을 공부하고 지금 프로젝트에 맞는 schema 설계하기

## To do
- [ ] 몽고DB schema 에 대해서 공부
- [ ] 프로젝트에 필요한 schema 구상 및 설계

**Comment by developerasun** [comment]
스키마 설정하고 어떤 것들이 필요하지는 같이 고민해봐야 할 것 같아유 어떤식으로 시작할까요?

**Comment by developerasun** [comment]
https://dbdiagram.io/home 다이어그램 툴은 전에 말해줬던 이거 쓰면 될 거 같구

**Comment by omago123** [comment]
![image](https://user-images.githubusercontent.com/73014464/160814219-1b24138e-930b-403f-b8b1-25d995b048d6.png)
https://www.datensen.com/mongodb-design-tool.html

이거쓰면 몽고디비 스키마 디자인 될거 같은데요.

**Comment by omago123** [comment]
![image](https://user-images.githubusercontent.com/73014464/160849636-8eb1f421-e1ff-48f6-9eb2-9e00daa53b49.png)

**Comment by developerasun** [comment]
> ![image](https://user-images.githubusercontent.com/73014464/160814219-1b24138e-930b-403f-b8b1-25d995b048d6.png) https://www.datensen.com/mongodb-design-tool.html
> 
> 이거쓰면 몽고디비 스키마 디자인 될거 같은데요.

오 이것도 괜찮네유 - 

이거는 아이디어이긴 한데  [dummy user](https://jsonplaceholder.typicode.com/)들 DB에 저장해놓고 게임 캐릭터들에 대한 인기투표 실시하는 거 어떰? 

지금 게임 캐릭터는 #72 에서 보듯이 3개 있으니까 이 세 종류 인기투표 진행하고

그러면 우선 투표 수에 따라 몇 명의 유저가 어디에 투표했는지 DB 쿼리 날리고 정렬하고 할 수 있을 거 같은데

**Comment by omago123** [comment]
비밀번호 찾기 기능만들기

**Comment by omago123** [comment]
> > 비밀번호 찾기 기능만들기
> 
> 이거는 issue란 보다 discussion란에 올려서 계속 문서화하는 게 좋을 거 같은데 어떠신가유 ![convert](https://user-images.githubusercontent.com/83855174/160882310-4f6d8d34-55d0-465e-b017-f1b334c72a53.png)
