### ISSUE TITLE
[RESEARCH] Gizmos와 OnDrawGizmos()

### ISSUE THREAD

**Issue by jshhhhh** [DaeguDev/MeowRun#82]
# topic : Gizmos와 OnDrawGizmos()의 이해
## read this 
> ## Gizmos
> 기즈모(gizmo)는 시각적 디버깅 또는 씬뷰에서의 설정을 돕기위해 사용합니다.
> 모든 기즈모 그리기는 [OnDrawGizmos](https://docs.unity3d.com/kr/530/ScriptReference/MonoBehaviour.OnDrawGizmos.html) 또는 [OnDrawGizmosSelected](https://docs.unity3d.com/kr/530/ScriptReference/MonoBehaviour.OnDrawGizmosSelected.html) functions of the script.
[OnDrawGizmos](https://docs.unity3d.com/kr/530/ScriptReference/MonoBehaviour.OnDrawGizmos.html) 는 ```매 프레임마다 호출```됩니다. [OnDrawGizmos](https://docs.unity3d.com/kr/530/ScriptReference/MonoBehaviour.OnDrawGizmos.html) 내에 렌더되는 모든 기즈모들은 피킹가능합니다. [OnDrawGizmosSelected](https://docs.unity3d.com/kr/530/ScriptReference/MonoBehaviour.OnDrawGizmosSelected.html) 는 스크립트가 첨부된 해당 오브젝트가 선택되었을 경우에만 호출됩니다.

> ## OnDrawGizmos()
> ```선택할 수 있고 항상 화면에 나타나는 기즈모(gizmos)를 그리고 싶은 경우```에 OnDrawGizmos를 사용합니다.
씬(scene)에서 중요한 오브젝트를 빠르게 선택하는 경우에 매우 유용합니다.
OnDrawGizmos는 씬 뷰와 상대적인 마우스 위치를 사용한다는 점을 주의하십시오.
This function does not get called if the component is collapsed in the inspector. Use [OnDrawGizmosSelected](https://docs.unity3d.com/kr/530/ScriptReference/MonoBehaviour.OnDrawGizmosSelected.html) to draw gizmos when the game object is selected.
```cs
using UnityEngine;
using System.Collections;

public class ExampleClass : MonoBehaviour {
    void OnDrawGizmos() {
        Gizmos.color = Color.yellow;
        Gizmos.DrawSphere(transform.position, 1);
    }
}
```

## reference
- [Unity Documentation : Gizmos](https://docs.unity3d.com/kr/530/ScriptReference/Gizmos.html)
- [Unity Documentation : MonoBehaviour.OnDrawGizmos()](https://docs.unity3d.com/kr/530/ScriptReference/MonoBehaviour.OnDrawGizmos.html)

**Comment by developerasun** [comment]
개략적인 거는 이해하겠는데 이것도 역시 써봐야 알 것 같아유 텍스트만 읽으면 어떤 상황에서 '매우 유용'한지 와닿지는 않네
