### ISSUE TITLE
[BUG]  File may be corrupted or was serialized with a newer version of Unity.

### ISSUE THREAD

**Issue by jshhhhh** [DaeguDev/MeowRun#83]
# issue : merge 후 file corrupted
## screenshot : attach a screenshot showing the bug

* merge 후 clone으로 받아온 프로젝트에서 오류 발생
* 아래의 파일 목록들이 손상된 것으로 추정

![오류](https://user-images.githubusercontent.com/86046319/160787510-8f2e460a-2e61-4ab2-a0df-a4c24397cbe6.jpg)

## label : add propel lables for the bug

**Comment by developerasun** [comment]
1. 흠 이거 앞에 terrain 폴더에 들어있는 파일들은 #78 에서 언급했듯이 git lfs pull로 받아와야할 거에요 용량이 100MB 이상이라

```shell
$git lfs pull  
$git lfs ls-files
```

1. 뒤에 blender나 maya도 3D 에셋 관련 그래픽 툴인데 왜 뜨는지는 모르겠고.. 

1. 마지막에 new version unity가 문제면 제가 다운그레이드해볼게용

**Comment by jshhhhh** [comment]
> 1. 흠 이거 앞에 terrain 폴더에 들어있는 파일들은 [feat: 맵 아이템, 플랫폼, 지형 질감 추가 #78](https://github.com/DaeguDev/MeowRun/pull/78) 에서 언급했듯이 git lfs pull로 받아와야할 거에요 용량이 100MB 이상이라
> 
> ```shell
> $git lfs pull  
> $git lfs ls-files
> ```
> 
> 1. 뒤에 blender나 maya도 3D 에셋 관련 그래픽 툴인데 왜 뜨는지는 모르겠고..
> 2. 마지막에 new version unity가 문제면 제가 다운그레이드해볼게용

* #78 확인만 하고 적용 안 했었네.. 이 방식으로 다시 해보겠음
* 다운그레이드는 ㄴㄴ 나 버전 안 바꾸고 작업하는 중임

**Comment by jshhhhh** [comment]
## test : git lfs pull
* 새 폴더에 clone 후 lfs pull 완료

![git lfs pull](https://user-images.githubusercontent.com/86046319/160806517-51d3e06f-2714-4279-bb2b-ba96d385eff4.jpg)

* 오류 개수가 좀 줄어들긴 함

![image](https://user-images.githubusercontent.com/86046319/160806685-56d3785e-6b59-4d34-ae44-bd499d87ac76.png)
![image](https://user-images.githubusercontent.com/86046319/160806973-eee44dc7-548e-4024-9938-7bd978ac541c.png)

**Comment by developerasun** [comment]
이게 3D 에셋들이나 3D 지형 텍스처 같은 경우는 용량이 큰 경우가 많은데 그러면 lfs 사용해야 하고
아마 슬쩍 문서 읽어보니까 이것도 실제 데이터를 가리키는 포인터만 저장해놓고 사용자가 git lfs pull로 당겨올떄만 실 데이터를 주는 방식인 거 같더라구용?
