### ISSUE TITLE
[BUG] Git/version control : merge 이후 기존 scene 파일 사라짐

### ISSUE THREAD

**Issue by developerasun** [DaeguDev/MeowRun#89]
# issue : feature 브랜치 merge 이후 기존 scene 파일들이 초기화됨
## screenshot : attach a screenshot showing the bug
![merge-scene](https://user-images.githubusercontent.com/83855174/161047577-db059092-1d75-4daf-a989-089ca252f470.png)

@jshhhhh

**Comment by developerasun** [comment]
## 복구 idea 1
git log 확인 이후 해당 merge 이전으로 롤백. 롤백 이후 

- [ ] [릴리즈](https://github.com/DaeguDev/MeowRun/releases) 란에 업로드 해둘 것.

**Comment by jshhhhh** [comment]
## 복구 idea 2
- #91 pull 해보기
  - 해결이 안 되면 새 폴더에서 git clone, git lfs pull 해보기

**Comment by developerasun** [comment]
## 경과
#91 메인 브랜치 merge 이후 git pull origin 진행
![map-recover](https://user-images.githubusercontent.com/83855174/161647109-fa462ec9-730a-4991-943a-12c7b705c9db.png)

## 결론 
텍스처 제외 원상 복귀. 텍스처 파일 용량, git LFS 용량 제한 등을 고려해 3D 지형 맵 텍스처는 animation 만들때 함께 조절하는 것이 좋아보임
